import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import LoginForm from "../components/login/LoginForm";
import logo from "../../public/assets/vkLogo.png";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <LoginForm />
        <div className={styles.logoContainer}>
          <div className={styles.imageContainer}>
            <Image src={logo} width={104} height={140} alt={"miet vk logo"} />
          </div>

          <p>Военная кафедра МИЭТ</p>
        </div>
      </main>
    </div>
  );
};

export default Home;
